#!/usr/bin/env sh

# Base palette values are referenced by derived settings below.
BAR_COLOR=0xff1a1b26
BLACK=0xff24283b
BLUE=0xff7aa2f7
COMMENT=0xff565f89
CYAN=0xff7dcfff
GREEN=0xff9ece6a
MAGENTA=0xffbb9af7
RED=0xfff7768e
WHITE=0xffa9b1d6
YELLOW=0xffe0af68

# Shared SketchyBar settings.
BORDER_WIDTH=2
CAPSULE_HEIGHT=26
CAPSULE_PADDING=10
CORNER_RADIUS=15
FONT="JetBrainsMono Nerd Font"
HELPER_DIR="$HOME/.config/sketchybar/helpers"
HOVER_ANIMATION_DURATION=8
HOVER_BACKGROUND_COLOR=$BLACK
ICON_COLOR=$WHITE
ITEM_DIR="$HOME/.config/sketchybar/items"
LABEL_COLOR=$WHITE
PADDINGS=3
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$COMMENT
SHADOW=on
WIDGET_BORDER_COLOR=0xcc565f89
WIDGET_SPACING=4
WORKSPACE_ACTIVE_COLOR=$RED
WORKSPACE_HOVER_COLOR=$YELLOW
WORKSPACE_INACTIVE_COLOR=$COMMENT
WORKSPACE_TRANSITION=10
